### ISSUE TITLE
Watermark remover

### ISSUE THREAD

**Issue by BillTribble** [camenduru/text-to-video-synthesis-colab#12]
Won't run. Crashes like this:

`2023-06-01 15:36:38 (205 MB/s) - ‘/content/lama/indir/image_mask.png’ saved [8636/8636]

/content/lama
WARNING:py.warnings:/usr/local/lib/python3.10/dist-packages/gradio/deprecation.py:40: UserWarning: The 'type' parameter has been deprecated. Use the Number component instead.
  warnings.warn(value)

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-1-4bfb8c6d7a11>](https://localhost:8080/#) in <cell line: 88>()
     86     return final_vid
     87 
---> 88 with gr.Blocks() as demo:
     89     with gr.Column(elem_id="col-container"):
     90         with gr.Row():

2 frames
[/usr/local/lib/python3.10/dist-packages/gradio_client/serializing.py](https://localhost:8080/#) in input_api_info(self)
     39     def input_api_info(self) -> tuple[str, str]:
     40         api_info = self.api_info()
---> 41         return (api_info["serialized_input"][0], api_info["serialized_input"][1])
     42 
     43     # For backwards compatibility

KeyError: 'serialized_input'`

**Comment by camenduru** [comment]
thanks for the info @BillTribble ❤ please try again

**Comment by BillTribble** [comment]
Fixed - thanks so much!
