### ISSUE TITLE
 Launching Web UI with arguments: --listen --xformers --enable-insecure-extension-access --theme dark --gradio-queue --multiple --disable-safe-unpickle

### ISSUE THREAD

**Issue by almfahd41** [camenduru/text-to-video-synthesis-colab#21]
Launching Web UI with arguments: --listen --xformers --enable-insecure-extension-access --theme dark --gradio-queue --multiple --disable-safe-unpickle
src/tcmalloc.cc:283] Attempt to free invalid pointer 0x5bdd20789740

**Comment by camenduru** [comment]
please try again
