### ISSUE TITLE
Runtime environment crushes after RAM usage goes over 12GB

### ISSUE THREAD

**Issue by volotat** [camenduru/text-to-video-synthesis-colab#3]
I tired to generate anything using this colab but each time it crushes after system RAM goes over 12GB. Is there any way to mitigate this problem via controlling number of frames generated or the size of the frame?

**Comment by camenduru** [comment]
Hi @volotat 👋 please try again maybe works and if modelscope developers add new features I will add we are using [this](https://github.com/modelscope/modelscope/blob/master/modelscope/pipelines/multi_modal/text_to_video_synthesis_pipeline.py) pipeline and thanks ❤ for the https://github.com/volotat/Reference-based-SD-CN-Animation look super cool 🔥 I will try

**Comment by camenduru** [comment]
and you can edit max_frames please check https://huggingface.co/camenduru/text-to-video-synthesis/blob/main/hub/damo/text-to-video-synthesis/configuration.json `/root/.cache/modelscope/hub/damo/text-to-video-synthesis/configuration.json`

**Comment by camenduru** [comment]
please watch this https://www.youtube.com/watch?v=b8D4am73e6I

**Comment by volotat** [comment]
Thank you a lot for a quick response and the video. It does work now.
