### ISSUE TITLE
Your session crashed for an unknown reason.

### ISSUE THREAD

**Issue by tralala87** [camenduru/text-to-video-synthesis-colab#4]
getting this error after recent update to the .ipynb file

`Your session crashed for an unknown reason.`

**Comment by camenduru** [comment]
Hi @tralala87 👋 I am working on it

**Comment by camenduru** [comment]
please try again maybe I fixed the ram problem

**Comment by tralala87** [comment]
yep, still persist.. unknown reason

**Comment by camenduru** [comment]
please watch this https://www.youtube.com/watch?v=b8D4am73e6I
