### ISSUE TITLE
[Google Colab] Format of output video cannot play in some contexts

### ISSUE THREAD

**Issue by CarbonatedPastries** [camenduru/text-to-video-synthesis-colab#6]
The current `export_to_video` function from HuggingFace encodes the output video with `MPEG-4 Visual` format, which doesn't play in some contexts such as Desktop Discord. (They can play in normal video players and mobile Discord.) Looking at the [HuggingFace Space version](https://huggingface.co/spaces/damo-vilab/modelscope-text-to-video-synthesis/blob/main/app.py), they are using `imageio` to export, which results in a video file with `AVC` format.

Could the colab be adjusted so the output format is functional in more contexts?

**Comment by camenduru** [comment]
thanks @CarbonatedPastries ❤please try it https://github.com/camenduru/text-to-video-synthesis-colab/commit/3cd036e26cf65c8725aa9a494f3a2e6c7bb1a9ad

**Comment by CarbonatedPastries** [comment]
Tested and outputs can play in Desktop Discord. Thanks!
