### ISSUE TITLE
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. pandas-gbq 0.17.9 requires pyarrow<10.0dev,>=3.0.0, but you have pyarrow 11.0.0 which is incompatible.

### ISSUE THREAD

**Issue by ELO2023** [camenduru/text-to-video-synthesis-colab#7]
Attempted to run text_to_video_synthesis.ipynb

I have been getting this error: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pandas-gbq 0.17.9 requires pyarrow<10.0dev,>=3.0.0, but you have pyarrow 11.0.0 which is incompatible.

![Screenshot 2023-04-04 214428](https://user-images.githubusercontent.com/129917900/229967866-99338a03-c804-4225-a79c-59d9b815567f.jpg)

How would I downgrade the pyarrow from 11.0.0 to pyarrow<10.0dev,>=3.0.0 can someone help me with this error.

**Comment by camenduru** [comment]
thanks @ELO2023 ❤ maybe fixed please try again
